import Head from 'next/head'
import Header from '../Components/Header'
import Nav from '../Components/Nav'
import Results from '../Components/Results'
import requests from '../utils/requests'

export default function Home({results}) {
  return (
    <>
      <Head>
        <title>Hulu Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <Header/>
     <Nav/>
     <Results results={results}/>
     
    </>
  )
}


export async function getServerSideProps(context){
  const genre = context.query.genre;

  const request = await fetch(`https://api.themoviedb.org/3${requests[genre]?.url
   || requests.fetchTrending.url}`)
   .then(res=>res.json());

   return {
    props:{
      results:request.results
    }

   }


  
}